apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec33nw-map-gui
  labels:
    app: ec33nw-map-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ec33nw-map-gui
  template:
    metadata:
      labels:
        app: ec33nw-map-gui
    spec:
      containers:
        - name: ec33nw-map-gui
          image: zedas/ec33nw-map-gui
          ports:
            - containerPort: 80
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ec33nw-map-gui-service
spec:
  selector:
    app: ec33nw-map-gui
  type: LoadBalancer
  ports:
    - port: 80
      name: defaultnginxport
      protocol: TCP
      targetPort: 80
      nodePort: 30080
