/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BalanceSheet { 
    accountsPayable?: number;
    capitalSurplus?: number;
    commonStock?: number;
    currency?: string;
    currentAssets?: number;
    currentCash?: number;
    currentLongTermDebt?: number;
    date?: number;
    filingType?: string;
    fiscalDate?: string;
    fiscalQuarter?: number;
    fiscalYear?: number;
    goodwill?: number;
    id?: string;
    intangibleAssets?: number;
    inventory?: number;
    key?: string;
    longTermDebt?: number;
    longTermInvestments?: number;
    minorityInterest?: number;
    netTangibleAssets?: number;
    otherAssets?: number;
    otherCurrentAssets?: number;
    otherCurrentLiabilities?: number;
    otherLiabilities?: number;
    propertyPlantEquipment?: number;
    receivables?: number;
    reportDate?: string;
    retainedEarnings?: number;
    shareholderEquity?: number;
    shortTermInvestments?: number;
    subkey?: string;
    symbol?: string;
    totalAssets?: number;
    totalCurrentLiabilities?: number;
    totalLiabilities?: number;
    treasuryStock?: number;
    updated?: number;
}

