/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CashFlow { 
    capitalExpenditures?: number;
    cashChange?: number;
    cashFlow?: number;
    cashFlowFinancing?: number;
    changesInInventories?: number;
    changesInReceivables?: number;
    currency?: string;
    date?: number;
    depreciation?: number;
    dividendsPaid?: number;
    exchangeRateEffect?: number;
    filingType?: string;
    fiscalDate?: string;
    fiscalQuarter?: number;
    fiscalYear?: number;
    id?: string;
    investingActivityOther?: number;
    investments?: number;
    key?: string;
    netBorrowings?: number;
    netIncome?: number;
    otherFinancingCashFlows?: number;
    reportDate?: string;
    subkey?: string;
    symbol?: string;
    totalInvestingCashFlows?: number;
    updated?: number;
}

