/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CashFlow { 
    symbol?: string;
    id?: string;
    key?: string;
    subkey?: string;
    updated?: number;
    date?: number;
    reportDate?: string;
    fiscalDate?: string;
    currency?: string;
    netIncome?: number;
    depreciation?: number;
    changesInReceivables?: number;
    changesInInventories?: number;
    cashChange?: number;
    cashFlow?: number;
    capitalExpenditures?: number;
    investments?: number;
    investingActivityOther?: number;
    totalInvestingCashFlows?: number;
    dividendsPaid?: number;
    netBorrowings?: number;
    otherFinancingCashFlows?: number;
    cashFlowFinancing?: number;
    exchangeRateEffect?: number;
    filingType?: string;
    fiscalQuarter?: number;
    fiscalYear?: number;
}

