/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncomeStatement { 
    costOfRevenue?: number;
    currency?: string;
    date?: number;
    ebit?: number;
    filingType?: string;
    fiscalDate?: string;
    fiscalQuarter?: number;
    fiscalYear?: number;
    grossProfit?: number;
    id?: string;
    incomeTax?: number;
    interestIncome?: number;
    key?: string;
    minorityInterest?: number;
    netIncome?: number;
    netIncomeBasic?: number;
    operatingExpense?: number;
    operatingIncome?: number;
    otherIncomeExpenseNet?: number;
    pretaxIncome?: number;
    reportDate?: string;
    researchAndDevelopment?: number;
    sellingGeneralAndAdmin?: number;
    subkey?: string;
    symbol?: string;
    totalRevenue?: number;
    updated?: number;
}

